### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [rousmedina/lim-2018-05-bc-core-am-cipher#1]
**README**
* Ojo! Ten cuidado con la ortografía.

**UX**
* Para futuros proyectos, dale un poco de contexto al usuario que visita tu aplicación. Explíca cómo usarla o usa títulos y acciones descriptivas.

**HTML**
* No olvides validar tu HTML, revisa [esta URL](https://validator.w3.org/nu/?doc=https%3A%2F%2Frousmedina.github.io%2Flim-2018-05-bc-core-am-cipher%2Fsrc%2F) para que observes tus errores.
* Te sugerimos usar más etiquetas semánticas como `<header>`, `<footer>`.
* Para seguir buenas prácticas, te sugerimos definir los `id` y `clases` de elementos en minúsculas y separados por guiones (-).
* Te sugerimos incluir el atributo `alt` en imágenes para describir la imagen.

**JS**
* Tu aplicación no descifra cuando se usa números grandes (Ej: 1042) como offset. Te sugerimos que al momento de desarrollar alguna función trates de probar con varios números y hasta con valores o argumentos “extremos”. Recuerda que tu usuario puede "probar" con cualquier número.
* Recuerda que uno de los requerimientos del proyecto era estar implementado completamente en ES6, para ello, también deberías usar el `for..of`.
* Para proyectos futuros, te sugerimos seguir la [guía de estilos de Laboratoria sobre JS](https://github.com/Laboratoria/js-style-guide).

**TESTS**
* Siempre puedes desarrollar tests extra que te ayuden a probar con varios números y hasta con valores o argumentos “extremos”. Recuerda que tu usuario puede probar con cualquier número.

Buen trabajo!

**Comment by rousmedina** [comment]
Lo tendré en cuenta gracias
